global:

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'

  routes:
    - match:
        severity: critical
      receiver: 'telegram-critical'
    - match:
        severity: warning
      receiver: 'telegram-warning'

receivers:
  - name: 'default'

  - name: 'telegram-critical'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'token'
        chat_id: 238768019
        message: '{{ template "telegram.default.message" . }}'
        disable_notifications: false

  - name: 'telegram-warning'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'token'
        chat_id: 238768019 #не стал разделять на два разных канала, но смысл понятен
        message: '{{ template "telegram.default.message" . }}'
        disable_notifications: false

templates:
  - '/etc/alertmanager/template.tmpl'
