global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9100']

  - job_name: 'mariadb'
    static_configs:
      - targets: ['localhost:9104']

  - job_name: 'php-fpm'
    static_configs:
    - targets: ['localhost:9253']

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
      target: [http://localhost/]
    static_configs:
      - targets: ['localhost:9115']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: localhost:9115
